apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: aspire
  name: aspire
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: aspire
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml --out menifest/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: aspire
    spec:
      containers:
        - image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
          livenessProbe:
            exec:
              command:
                - curl
                - --silent
                - --fail
                - http://localhost:18888/metrics
            failureThreshold: 5
            periodSeconds: 10
          name: aspire-dashboard
          ports:
            - containerPort: 18888
              protocol: TCP
      restartPolicy: Always
