export const supportedLanguages = [
  { id: 'javascript', name: 'JavaScript', language_id: 63 },
  { id: 'typescript', name: 'TypeScript', language_id: 74 },
  { id: 'python', name: 'Python', language_id: 71 },
  { id: 'java', name: 'Java', language_id: 62 },
  { id: 'cpp', name: 'C++', language_id: 53 },
  { id: 'c', name: 'C', language_id: 50 },
  { id: 'html', name: 'HTML', language_id: 80 },
  { id: 'css', name: 'CSS', language_id: 43 },
  { id: 'sql', name: 'SQL', language_id: 82 },
  { id: 'php', name: 'PHP', language_id: 68 },
  { id: 'ruby', name: 'Ruby', language_id: 72 },
  { id: 'go', name: 'Go', language_id: 60 },
  { id: 'swift', name: 'Swift', language_id: 83 },
  { id: 'kotlin', name: 'Kotlin', language_id: 78 },
  { id: 'rust', name: 'Rust', language_id: 73 },
  { id: 'haskell', name: 'Haskell', language_id: 61 },
  { id: 'bash', name: 'Bash', language_id: 46 },
  { id: 'json', name: 'JSON', language_id: 80 }, // JSON can be embedded in HTML (language_id may vary)
  { id: 'lua', name: 'Lua', language_id: 64 },
  { id: 'dart', name: 'Dart', language_id: 87 },
  { id: 'r', name: 'R', language_id: 80 }, // Judge0 uses language_id 80 for R
  { id: 'vbnet', name: 'VB.NET', language_id: 84 },
];

export const languageTemplate: { [key: string]: string } = {
  javascript: `// JavaScript Template\nconsole.log('Hello, JavaScript!');`,
  typescript: `// TypeScript Template\nconsole.log('Hello, TypeScript!');`,
  python: `# Python Template\nprint('Hello, Python!')`,
  java: `// Java Template\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, Java!");\n    }\n}`,
  cpp: `// C++ Template\n#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << "Hello, C++!" << endl;\n    return 0;\n}`,
  c: `// C Template\n#include <stdio.h>\n\nint main() {\n    printf("Hello, C!\\n");\n    return 0;\n}`,
  html: `<!-- HTML Template -->\n<!DOCTYPE html>\n<html>\n<head>\n    <title>Hello, HTML!</title>\n</head>\n<body>\n    <h1>Hello, World!</h1>\n</body>\n</html>`,
  css: `/* CSS Template */\nbody {\n    font-family: Arial, sans-serif;\n    color: #333;\n}\nh1 {\n    text-align: center;\n    color: #555;\n}`,
  sql: `-- SQL Template\nSELECT * FROM users WHERE active = 1;`,
  php: `<?php\n// PHP Template\necho "Hello, PHP!";\n?>`,
  ruby: `# Ruby Template\nputs 'Hello, Ruby!'`,
  go: `// Go Template\npackage main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Hello, Go!")\n}`,
  swift: `// Swift Template\nimport Foundation\n\nprint("Hello, Swift!")`,
  kotlin: `// Kotlin Template\nfun main() {\n    println("Hello, Kotlin!")\n}`,
  rust: `// Rust Template\nfn main() {\n    println!("Hello, Rust!");\n}`,
  haskell: `-- Haskell Template\nmain :: IO ()\nmain = putStrLn "Hello, Haskell!"`,
  bash: `# Bash Template\necho "Hello, Bash!"`,
  json: `{\n  "message": "Hello, JSON!"\n}`,
  lua: `-- Lua Template\nprint("Hello, Lua!")`,
  dart: `// Dart Template\nvoid main() {\n  print('Hello, Dart!');\n}`,
  r: `# R Template\nprint("Hello, R!")`,
  vbnet: `' VB.NET Template\nModule Module1\n    Sub Main()\n        Console.WriteLine("Hello, VB.NET!")\n    End Sub\nEnd Module`,
};
