name: .NET CI/CD Workflow

on:
  push:
    branches:
      - main
      - development
      - feature/CD
  pull_request:
    branches:
      - main
      - development
      - feature/CD

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for Sonar analysis

      - name: Restore TenantConstants.cs Locally
        run: echo "${{ secrets._TENANT_CONSTANTS_CS }}" | base64 --decode > backend/Shared/Authorization/TenantConstants.cs

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"Learnathon-By-Geeky-Solutions_earendel" \
            /o:"learnathon-by-geeky-solutions" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.coverageReportPaths="CoverageReports/Cobertura.xml" \
            /d:sonar.cs.cobertura.reportPaths="CoverageReports/Cobertura.xml"

      - name: Restore Dependencies
        run: dotnet restore backend/Aspire/Aspire.sln

      - name: Build Application
        run: dotnet build backend/Aspire/Aspire.sln --configuration Release --no-restore

      - name: Run Tests with Coverage
        timeout-minutes: 15
        run: |
          mkdir -p test-results
          dotnet test backend/Aspire/Aspire.sln \
            --no-build \
            --configuration Release \
            --collect:"XPlat Code Coverage;Format=opencover" \
            --results-directory test-results

      - name: Generate Consolidated Coverage Report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator \
            -reports:"test-results/**/coverage.opencover.xml" \
            -targetdir:"CoverageReports" \
            -reporttypes:"Cobertura" \
            -title:"Code Coverage"

      - name: Validate Coverage File
        run: |
          echo "=== Coverage File Verification ==="
          ls -l "${{ github.workspace }}/CoverageReports/coverage.opencover.xml"
          echo "=== XML Validation ==="
          xmllint --noout "${{ github.workspace }}/CoverageReports/coverage.opencover.xml"

      - name: End SonarCloud Analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  publish:
    name: Publish Application
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore TenantConstants.cs Locally
        run: echo "${{ secrets._TENANT_CONSTANTS_CS }}" | base64 --decode > backend/Shared/Authorization/TenantConstants.cs

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Build and Publish
        run: dotnet publish backend/Api/Server/Server.csproj -c Release -o backend/Api/Server/publish

      - name: Upload Published Application
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: backend/Api/Server/publish/

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: publish
    timeout-minutes: 45

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Config Files
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_timeout: 600
          script: |
            echo "${{ secrets._APPSETTINGS }}" | base64 --decode > /root/Learnathon/earendel/backend/Api/Server/appsettings.json
            echo "${{ secrets._TENANT_CONSTANTS_CS }}" | base64 --decode > /root/Learnathon/earendel/backend/Shared/Authorization/TenantConstants.cs
            chmod 644 /root/Learnathon/earendel/backend/Api/Server/appsettings.json
            chmod 644 /root/Learnathon/earendel/backend/Shared/Authorization/TenantConstants.cs

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_timeout: 1800
          script: |
            cd /root/Learnathon/earendel
            git checkout main
            git pull origin main
            cd backend
            docker-compose down --timeout 300
            docker-compose up --build -d --timeout 600